# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=24)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('tweet_id', models.CharField(max_length=24)),
                ('tweet_date', models.DateTimeField()),
                ('tweet_text', models.CharField(max_length=280)),
                ('classification', models.CharField(max_length=1)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweet.Search')),
            ],
        ),
    ]
