# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('tweet_id', models.CharField(max_length=24)),
                ('tweet_date', models.DateField()),
            ],
        ),
    ]
