# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='name',
        ),
        migrations.AddField(
            model_name='tweet',
            name='classification',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
