# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 15:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20180806_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='search',
            field=models.CharField(default=datetime.datetime(2018, 8, 6, 15, 3, 23, 880669, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_date',
            field=models.DateTimeField(),
        ),
    ]
